stages:
  - performance_test

performance_test_stage:
  stage: performance_test
  image:
    name: node:lts-alpine
  before_script:
    - npm i
    - npm run build
  script:
    - mkdir output
    - npx playwright install chrome
    - npx artillery run -c config.yml -o output/result.json scenarios/web.yml
    - npx artillery report --output output/result.html output/result.json
  artifacts:
    paths:
      - output
