stages:
  - performance_test

performance_test_stage:
  stage: performance_test
  image:
    name: mcr.microsoft.com/playwright:jammy
  before_script:
    - npm i
    - npm run build
  script:
    - mkdir output
    - npx artillery run -c config.yml -o output/result.json scenarios/web.yml
    - npx artillery report --output output/result.html output/result.json
  only:
    - main
    - master
  tags:
    - saas-linux-medium-amd64
  artifacts:
    paths:
      - output
