config:
  target: "https://tructuyen.abic.com.vn"
  phases:
    - name: "Single user"
      arrivalRate: 50
      duration: 120
  payload:
    path: ./data/users.csv
    fields:
      - fullName
      - phoneNumber
      - email
      - city
      - address
      - licensePlates
  engines:
    playwright:
      launchOptions:
        headless: true
  processor: ./flows/abic.js
