config:
  target: "https://tructuyen.abic.com.vn"
  phases:
    - name: "100 users in 1 minute"
      arrivalCount: 100
      duration: 60
  payload:
    path: ./data/users.csv
    fields:
      - fullName
      - phoneNumber
      - email
      - city
      - address
      - licensePlates
  engines:
    playwright:
      launchOptions:
        headless: true
  processor: ./flows/abic.js
