# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main", "master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  load-testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:jammy

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies & build
        run: |
          npm i
          npm run build
      - name: Run load testing
        run: |
          mkdir output
          npx artillery run -c config.yml -o output/result.json scenarios/web.yml
          npx artillery report --output output/result.html output/result.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: testing-results
          path: output/
